### ISSUE TITLE
bdic file support

### ISSUE THREAD

**Issue by conlank** [glutanimate/hunspell-en-med-glut-workaround#1]
I created an en_US.bdic file for those who are using a spell checker that prefers that file format or want to use this dictionary with chrome. 
[en_US.bdic.zip](https://github.com/glutanimate/hunspell-en-med-glut-workaround/files/5714271/en_US.bdic.zip)

**Comment by a100dollarbill** [comment]
I love you please have my babies

**Comment by DoctorToBeIn23** [comment]
THANNNNNNNK YOU!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by glutanimate** [comment]
Thanks for the share :)

For those of you coming in from Anki: I've been working on an updated version of my dictionary here (which is 7 years old by now), and will be bundling it with my [Spell Checker add-on for Anki](https://github.com/glutanimate/spell-checker-public) in its next release.
